version: "3.9"

services:

  firestore:
    image: mtlynch/firestore-emulator:latest
    ports:
      - "8080:8080"
    environment:
      FIRESTORE_PROJECT_ID: glass-record-dev
      PORT: 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5
